import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  domains,
}: Readonly<{
  children: React.ReactNode;
  domains: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="bg-blue-100 p-6 rounded-xl">{domains}</div>
          <div className="bg-green-100 p-6 rounded-xl">Cell 2</div>
          <div className="bg-yellow-100 p-6 rounded-xl">Cell 3</div>
          <div className="bg-red-100 p-6 rounded-xl">Cell 4</div>
        </div>
        {children}
      </body>
    </html>
  );
}
